# Generated by Django 5.2.5 on 2025-10-09 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_current_bid_alter_bid_highest_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='opened',
        ),
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
